apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projetosd-blue
spec:
  replicas: 12
  template:
    metadata:
      labels:
        type: projetosd
    spec:
      containers:
      - image: nathanmrtns/projetosd:v2
        name: projetosd
        ports:
        - containerPort: 80
          name: http-server
